fixing buildspec.yml

diff --git a/buildspec.yml b/buildspec.yml
--- a/buildspec.yml
+++ b/buildspec.yml
@@ -10,7 +10,22 @@ phases:
   build:
     commands:
       - pre-commit run --all-files
-      - cd "$CODEBUILD_SRC_DIR/aws-lightsail-instance"
-      - mvn clean verify --no-transfer-progress
-    finally:
-      - cat "$CODEBUILD_SRC_DIR/aws-lightsail-instance/rpdk.log"
+      - |
+        if [ "$(ls -A $CODEBUILD_SRC_DIR)" ]; then
+          cd $CODEBUILD_SRC_DIR
+          # skip hidden folders
+          dirs=$(find . -not -path "\./\.*" -mindepth 1 -maxdepth 1 -type d)
+          echo "Folders to build: $dirs"
+          for directory in $dirs; do
+            cd "$directory"
+            mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B clean verify --no-transfer-progress
+            if [ "$?" -ne 0 ] ; then
+                echo "Build failed!"
+                exit 1
+            else
+                cd ".."
+            fi
+          done
+        else
+          echo "$CODEBUILD_SRC_DIR is empty"
+        fi
